import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";


import Nav from '@/components/navigation/nav'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}> */}
      <body className={cn(
          "px-6 md:px-12 max-w-7xl mx-auto",                        // example override
          geistSans.variable,                  // your font CSS variable
          geistMono.variable,
          "antialiased"                        // always include this
        )}>
        <Nav></Nav>
        {children}
      </body>
    </html>
  );
}
