import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";


import Nav from '@/components/navigation/nav'
import { ThemeProvider } from "@/components/providers/theme-provider";
import Toaster from "@/components/ui/toaster";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}> */}
      <body className={cn(
          "px-6 md:px-12 max-w-7xl mx-auto",                        // example override
          geistSans.variable,                  // your font CSS variable
          geistMono.variable,
          "antialiased"                        // always include this
        )}>
          <ThemeProvider 
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
              <div className="flex-grow px-6 md:px-12 mx-auto max-w-8*l">
                <Nav></Nav>
                <Toaster></Toaster>
                {children}
              </div>
          </ThemeProvider>
      </body>
    </html>
  );
}
